### ISSUE TITLE
appearance tab to decide box width

### ISSUE THREAD

**Issue by amedeux** [bfritscher/carnac#16]
https://github.com/Code52/carnac/ features an appearance tab that let's you decide the width of the pop up boxes showing keystrokes, so one could place the key strokes in a row, rather than in a column. Is this a possibility on this fork? Is this something I can achieve by somehow editing "Carnac.exe.config"?
Thanks!

**Comment by bfritscher** [comment]
Yes, its the keyboard tab.

**Comment by amedeux** [comment]
Aw, sorry. Thanks for your patience.
