### ISSUE TITLE
Disable "Show Mouse Clicks" does not work

### ISSUE THREAD

**Issue by todrich** [bfritscher/carnac#31]
Mouse clicks still display when this option is unchecked. Windows 10 1909, build 18363.1082.

**Comment by bfritscher** [comment]
Hi some options do not apply directly and require to click save or even restart the tool :-(

**Comment by marco-rivera-vfx** [comment]
I´m having the same issue. Even saving and restarting.

**Comment by marco-rivera-vfx** [comment]
I was using an older release. It´s working fine.
