### ISSUE TITLE
Keymaps for mouse

### ISSUE THREAD

**Issue by Desaydrone** [bfritscher/carnac#6]
Hello,

I love your version of carnac, thanks for your work
I use a personal keymap for some app, and i need for exemple to made SHIFT + Left mouse click, i don't find how to do it ? Is this exist ?

**Comment by bfritscher** [comment]
Yes, they are mapped to theses names:
![image](https://user-images.githubusercontent.com/338973/79987678-04ec6a80-84ae-11ea-9e7f-26c25ec75ae9.png)

`Ctrl+Shift+LButton` Should work

**Comment by Desaydrone** [comment]
Ho yes thanks so much !!!

**Comment by candideu** [comment]
Hello! What are the keymaps for arrows?

**Comment by bfritscher** [comment]
Should be Up, Down, Left, Right
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.keys?view=net-5.0

**Comment by candideu** [comment]
> Should be Up, Down, Left, Right
> https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.keys?view=net-5.0

Perfect, thank you! Works like a charm.
