### ISSUE TITLE
[ENHANCEMENT] Be able to disable Mouse Interaction

### ISSUE THREAD

**Issue by dschiller** [bfritscher/carnac#8]
Make it possible to disable Mouse Interactions so that the Mosue Gestures are not displayed. Same for Keyboard. So that one can decide to Show the Keyboard, the Mouse or both.

**Comment by bfritscher** [comment]
This can already be done in the current release under mouse options
https://github.com/bfritscher/carnac/releases/tag/v3.1-beta

with
- show mouse clicks
- show clicks as key
